format = """
$username\
$hostname\
$localip\
$directory\
$nix_shell\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$fill\
$aws\
$cmd_duration\
$line_break\
$jobs\
$character"""

[aws]
symbol = " "
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
expiration_symbol = " "

[character]
vimcmd_symbol = "[🅽 ](bold blue)"

[directory]
read_only = ""

[docker_context]
symbol = "☸ "

[elixir]
symbol = " "
format = '[$symbol($version \(OTP $otp_version\) )]($style)'
disabled = false

[erlang]
format = "[$symbol($version )]($style)"

[fill]
symbol = " "

[git_branch]
symbol = " "
style = "red"
truncation_length = 32

[git_commit]
tag_symbol = " "

[git_status]
style = "bold bright-red"

[java]
symbol = " "
format = "[${symbol}(${version} )]($style)"

[localip]
disabled = false

[lua]
symbol = " "
format = "[$symbol($version )]($style)"

[nix_shell]
symbol = ""
format = '[$symbol nix]($style) '
style = "blue"

[nodejs]
format = "[$symbol($version )]($style)"

[package]
disabled = true
symbol = " "
format = "at [$symbol$version]($style) "
style = "yellow"

[python]
format = " "

[ruby]
symbol = " "
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
format = "[$symbol($version )]($style)"

[scala]
symbol = " "
format = "[${symbol}(${version} )]($style)"

[terraform]
symbol = " "
