#!/usr/bin/env bash

gap=12

yabai -m config layout bsp

yabai -m config top_padding    $gap
yabai -m config bottom_padding $gap
yabai -m config left_padding   $gap
yabai -m config right_padding  $gap
yabai -m config window_gap     $gap

yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^Software Update$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
